[package]
name = "raytracer-app"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[dependencies]
raytracer = { path = ".." }
serde = "0.9.7"
serde_json = "0.9.6"
clap = "2.20"
image = "0.12.3"
